/**
 * CiteKit — TypeScript interfaces and types.
 *
 * These mirror the Python SDK's Pydantic models exactly,
 * so maps generated by either SDK are cross-compatible.
 */

/** Physical location within a resource. */
export interface Location {
    modality: "document" | "video" | "audio" | "image";

    /** Document: 1-indexed page numbers. */
    pages?: number[];

    /** Video/Audio: start time in seconds. */
    start?: number;

    /** Video/Audio: end time in seconds. */
    end?: number;

    /** Image: normalized bounding box [x1, y1, x2, y2] (0.0–1.0). */
    bbox?: [number, number, number, number];
}

/** A concept or section within a resource. */
export interface Node {
    /** Dot-separated identifier, e.g. "derivatives.definition". */
    id: string;

    /** Human-readable title. */
    title?: string;

    /** Node type: definition, example, explanation, diagram, etc. */
    type: string;

    /** Where this node lives in the resource. */
    location: Location;

    /** 1-2 sentence summary. */
    summary?: string;

    /** Nested nodes. */
    children?: Node[];
}

/** Structured map of a resource — the first output of ingestion. */
export interface ResourceMap {
    resource_id: string;
    type: "document" | "video" | "audio" | "image";
    title: string;
    source_path: string;
    metadata?: Record<string, string | number | null>;
    nodes: Node[];
    created_at: string; // ISO 8601
}

/** Result of resolving a node. */
export interface ResolvedEvidence {
    /** Path to the extracted file (mini-PDF, clip, crop, etc.) */
    output_path: string;
    modality: string;
    /** URI-style address, e.g. doc://book#pages=12-13 */
    address: string;
    node: Node;
    resource_id: string;
}
